// ... existing code ...
        const query = 'experimental photography';
        const count = 6;
        // FIX: Correct Unsplash API URL
        const apiUrl = `https://api.unsplash.com/photos/random?query=${encodeURIComponent(query)}&count=${count}&client_id=${UNSPLASH_ACCESS_KEY}`;
        // ... existing code ...
                const apiKey = "AIzaSyA7rlussqhkkqn8wTFhTJY_R4AMC24-Bs4"; // Updated Gemini API key
        // ... existing code ...
            } catch (error) {
                console.error("Gemini API Error:", error);
                results.innerHTML = '<p class="text-red-500">Sorry, the muse is quiet right now. Please try again later.<br><span style="font-size:0.9em;">' + error.message + '</span></p>';
            } finally {
// ... existing code ...
